.TH cumsay 1
.SH NAME
cumsay <text_to_ejaculate>
.SH SYNOPSIS
.B cumsay
[\fIOPTIONAL_ARGS\fR]... [\fIOPTION\fR]...
.SH DESCRIPTION
.B cumsay
Usage: cumsay <text_to_ejaculate> Alternatively you can pipe input eg. cat example.txt | cumsay --colour red
.SH OPTIONS
.TP
.BR -h ", " --help
Show help message and exit.
.TP
.BR -v ", " --version
Show version number and exit.
.TP
.BR -c ", " --colour
Change the colour of the cum.
.TP
.BR -r ", " --rainbow
Make the cum rainbow.
.SH EXAMPLES
cumsay Hello World

.B Output:

.nf
/‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒\\

          Hello World

\\‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒/
                ____     _/
______     ___.'  o `.  /
/~----,\\___/,--.   ,_ |
        `-----'   `---'
.fi

echo "Man, I love cum!" |  cumsay 

.B Output:

.nf
/‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒\\

          Man, I love cum!

\\‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒/
                ____     _/
______     ___.'  o `.  /
/~----,\\___/,--.   ,_ |
        `-----'   `---'
.fi

.SH AUTHOR
Written by \fBXDGRC\fR.
.SH REPORTING BUGS
Report bugs to: @meowfemboy on Discord
.SH COPYRIGHT
Copyright © 2023 XDGRC
.SH LICENSE
This is free software: you are free to change and redistribute it under the terms of the \fBWhy The Fuck Would You Even Do That Holy Shit Public License\fR.
.SH CREDITS
Credit is due to
.B LotusTheFemboy
for the briliant idea as well as to 
.B Sparkster
.SM (S4ltster on github and also reachable on Discord as "Mr Green#8652")
for fixing the code. 
Credit is also due to 
.B Deltara
for porting to Arch Linux and making 
.B cumsay
availible for femboys.
.SH "SEE ALSO"
.BR cowsay (1)
